server:
  port: 8083 #puerto de app

spring:
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 1234

#p1
auth:
  auth-header: Authorization
  prefix: Bearer
  claim: authorities
  secret:
    key: keydemo
