server:
  port: 8082 #puerto de app

# endpoint de base datos
data-access-layer-bd: http://localhost:8083/users-dal

# p2
auth:
  auth-header: Authorization
  prefix: Bearer
  claim: authorities
  secret:
    key: keydemo

